podinfo:

  ingress:
    enabled: true
    className: ""
    annotations:
      route.openshift.io/termination: "edge"

  securityContext:
    runAsNonRoot: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 512Mi
