podinfo:

  ingress:
    enabled: true
    className: "openshift-default"
    annotations:
      route.openshift.io/termination: "edge"
    hosts:
    - host: ""
      paths:
      - path: /
        pathType: ImplementationSpecific

  securityContext:
    runAsNonRoot: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 512Mi
